name: test deploy

on:
  push:
    branches:
      - master  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install deps
        run: pip install -r requirements.txt
      - name: test
        run: pytest
  deploy:
    runs-on: my-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploy
        run: killall fastapi |true
      - name: run
        run: fastapi run& 

